snd-soc-opencores-i2s-objs := opencores_i2s.o
obj-$(CONFIG_SND_SOC_OPENCORES_I2S) += snd-soc-opencores-i2s.o

snd-soc-socfpga-wm8731-objs := socfpga-wm8731.o
obj-$(CONFIG_SND_SOC_SOCFPGA_WM8731) += snd-soc-socfpga-wm8731.o

